[package]
name = "kusa-monitor"
version = "0.0.0"
authors = ["The KUSA Developers"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.59"

[dependencies.web-sys]
version = "0.3.36"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]
